import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.json':'application/json','.txt':'text/plain'};
let assets={};for(let name of ['index.html','game.js','style.css',...fs.readdirSync('dist/assets').map(n=>'assets/'+n)]){const body=fs.readFileSync('dist/'+name);assets['/'+name]=[mime[path.extname(name)],body.toString('base64'),'"'+createHash('sha256').update(body).digest('hex')+'"'];}
// Fingerprints are computed from delivered bytes; dependent URLs change with their content.
const put=(name,body)=>{const bytes=Buffer.from(body);assets['/'+name]=[mime[path.extname(name)],bytes.toString('base64'),'"'+createHash('sha256').update(bytes).digest('hex')+'"']};
const versioned=name=>name+'?v='+assets['/'+name][2].slice(1,-1);
const manifest=JSON.parse(fs.readFileSync('dist/assets/manifest.json','utf8'));
for(const key of Object.keys(manifest))if(assets['/'+manifest[key]])manifest[key]=versioned(manifest[key]);
put('assets/manifest.json',JSON.stringify(manifest));
put('game.js',fs.readFileSync('dist/game.js','utf8').replaceAll('assets/manifest.json',versioned('assets/manifest.json')));
put('index.html',fs.readFileSync('dist/index.html','utf8').replace(/((?:src|href)=["'])([^"'?#]+)(["'])/g,(match,prefix,name,suffix)=>assets['/'+name]?prefix+versioned(name)+suffix:match));
fs.mkdirSync('dist/server',{recursive:true});fs.mkdirSync('dist/.openai',{recursive:true});fs.copyFileSync('.openai/hosting.json','dist/.openai/hosting.json');fs.cpSync('drizzle','dist/.openai/drizzle',{recursive:true});
fs.writeFileSync('dist/server/index.js',(fs.readFileSync('server/catalog.mjs','utf8')+'\n'+fs.readFileSync('server/api.mjs','utf8').replace(/^import .*;\r?\n/, '')).replaceAll('export const','const').replaceAll('export async function','async function').replaceAll('export function','function')+'\nconst assets='+JSON.stringify(assets)+';\nexport default {async fetch(request,env){const response=await api(request,env);if(response)return response;const u=new URL(request.url);const asset=assets[u.pathname==="/"?"/index.html":u.pathname];if(!asset)return new Response("Not found",{status:404});const headers={"Content-Type":asset[0],"Cache-Control":u.pathname!=="/"&&u.pathname!=="/index.html"&&u.searchParams.get("v")===asset[2].slice(1,-1)?"public, max-age=31536000, immutable":"no-cache",ETag:asset[2]};const tags=(request.headers.get("If-None-Match")||"").split(",").map(x=>x.trim().replace(/^W\\//,""));if((request.method==="GET"||request.method==="HEAD")&&(tags.includes(asset[2])||tags.includes("*")))return new Response(null,{status:304,headers});return new Response(request.method==="HEAD"?null:un64(asset[1]),{headers})}};');console.log('Worker built with '+Object.keys(assets).length+' assets.');
